dist: trusty
sudo: false
language: python

python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  # - "pypy"  # disable pypy builds until supported by trusty containers

install:
  - pip install --requirement tests/requirements.txt
  - pip install cython

script:
  - py.test -v tests --cov base62 --durations=10
  - python setup.py build_ext  # make sure the cythonized code is built

after_success:
  - coveralls
